name: linter
on: push
env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: make lint
        run: make lint
      - name: Run test
        run: make test
